name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Tag Image
      run: |
        docker build -t rbesar/belajar-app:1.0 -f Dockerfile .
    
    - name: Push to Dockerhub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_SECRET}} && docker push rbesar/belajar-app:1.0
      
      
      
